// Eingebaute Kategorien, leicht und schwer gemischt. Eigene kommen zur Laufzeit dazu.

export const CATEGORIES = [
  "Tiere",
  "Dinge auf einem Schiff",
  "Städte in Europa",
  "Was man im Urlaub vergisst",
  "Farben",
  "Obst",
  "Gemüse",
  "Getränke",
  "Berufe",
  "Sportarten",
  "Musikinstrumente",
  "Kleidungsstücke",
  "Möbel",
  "Körperteile",
  "Fahrzeuge",
  "Wetterlagen",
  "Feiertage",
  "Schulfächer",
  "Hobbys",
  "Blumen",
  "Bäume",
  "Vögel",
  "Fische",
  "Insekten",
  "Hunderassen",
  "Länder",
  "Hauptstädte",
  "Flüsse",
  "Meere und Ozeane",
  "Inseln",
  "Berge",
  "Städte in Deutschland",
  "Speisen",
  "Süßigkeiten",
  "Backwaren",
  "Frühstücksdinge",
  "Pizzabeläge",
  "Eissorten",
  "Käsesorten",
  "Brotbeläge",
  "Küchengeräte",
  "Werkzeuge",
  "Gartendinge",
  "Dinge im Badezimmer",
  "Dinge in der Küche",
  "Dinge im Wohnzimmer",
  "Dinge im Schlafzimmer",
  "Dinge im Kinderzimmer",
  "Dinge im Büro",
  "Dinge in der Schule",
  "Dinge im Krankenhaus",
  "Dinge auf einem Bauernhof",
  "Dinge am Strand",
  "Dinge im Wald",
  "Dinge im Zoo",
  "Dinge im Park",
  "Dinge im Supermarkt",
  "Dinge an der Tankstelle",
  "Dinge im Flugzeug",
  "Dinge im Zug",
  "Campingausrüstung",
  "Wintersportarten",
  "Sommerspiele draußen",
  "Ballspiele",
  "Brettspiele",
  "Kartenspiele",
  "Kinderspiele",
  "Märchen",
  "Zeichentrickfiguren",
  "Filmgenres",
  "Lieder, die alle kennen",
  "Märchenfiguren",
  "Berühmte Gebäude",
  "Sehenswürdigkeiten",
  "Museen-Exponate",
  "Dinge, die piepsen",
  "Dinge, die rund sind",
  "Dinge, die weich sind",
  "Dinge, die stinken",
  "Dinge, die glänzen",
  "Rote Dinge",
  "Gelbe Dinge",
  "Grüne Dinge",
  "Dinge mit Rädern",
  "Dinge aus Holz",
  "Dinge aus Glas",
  "Dinge aus Papier",
  "Dinge aus Metall",
  "Dinge, die man wirft",
  "Dinge, die man trägt",
  "Dinge, die man öffnet",
  "Dinge mit Knöpfen",
  "Dinge mit einem Bildschirm",
  "Dinge, die schwimmen",
  "Dinge, die fliegen",
  "Dinge, die man verliert",
  "Dinge in einer Handtasche",
  "Dinge in einer Brotdose",
  "Dinge auf einem Schreibtisch",
  "Dinge unter dem Bett",
  "Dinge im Kühlschrank",
  "Dinge im Keller",
  "Dinge auf dem Dachboden",
  "Dinge an der Wand",
  "Dinge, die man leiht",
  "Dinge, die man sammelt",
  "Geschenkideen",
  "Party-Spiele",
  "Karnevalskostüme",
  "Weihnachtsdinge",
  "Osterthemen",
  "Sommerurlaub",
  "Winterurlaub",
  "Campingplätze-Geräusche",
  "Was man am Meer macht",
  "Was man im Schnee macht",
  "Was man am Wochenende macht",
  "Was man vor dem Schlafen macht",
  "Was man morgens vergisst",
  "Ausreden fürs Zuspätkommen",
  "Gute Vorsätze",
  "Ängste",
  "Glücksbringer",
  "Superkräfte",
  "Märchenorte",
  "Planeten und Weltall",
  "Wetterphänomene",
  "Naturkatastrophen",
  "Verkehrsschilder-Themen",
  "Straßenverkehr",
  "Berufe im Krankenhaus",
  "Berufe in der Schule",
  "Berufe auf See",
  "Dinge in einem Werkzeugkasten",
  "Dinge in einem Erste-Hilfe-Kasten",
  "Dinge in einem Koffer",
  "Dinge in einem Rucksack",
  "Dinge auf einem Spielplatz",
  "Dinge in einer Turnhalle",
  "Dinge in einem Schwimmbad",
  "Dinge in einer Bibliothek",
  "Dinge in einem Restaurant",
  "Dinge in einer Bäckerei",
  "Dinge auf einem Markt",
  "Dinge in einem Zelt",
  "Dinge auf einer Baustelle",
  "Dinge in einem Museum",
  "Dinge in einem Theater",
  "Dinge bei einem Konzert",
  "Dinge auf einem Bauernmarkt",
  "Bauernhof-Tiere",
  "Zootiere",
  "Meerestiere",
  "Waldtiere",
  "Haustiere",
  "Dinosaurier",
  "Märchenwesen",
  "Helden aus Geschichten",
  "Schulfeste-Stände",
  "Pausenhof-Spiele",
  "Was Lehrer sagen",
  "Was Eltern sagen",
  "Dinge, die man üben muss",
  "Dinge, die knacken",
  "Dinge, die kleben",
  "Dinge, die tropfen",
  "Heiße Dinge",
  "Kalte Dinge",
  "Laute Dinge",
  "Leise Dinge",
  "Schwere Dinge",
  "Leichte Dinge",
  "Dinge mit einem Deckel",
  "Dinge mit einer Schnur",
  "Dinge zum Verschenken",
  "Dinge zum Ausleihen",
  "Orte zum Verstecken",
  "Orte zum Warten",
  "Orte mit einer Schlange",
  "Dinge, die man nicht anfassen soll",
  "Was im Märchen verboten ist",
];
